repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: end-of-file-fixer
        - id: name-tests-test
          args: [--django]
        - id: check-json
        - id: check-toml
        - id: check-yaml
          args: [--unsafe]
        - id: check-xml
        - id: check-added-large-files
        - id: pretty-format-json
          args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys", "--indent", "4"]

    - repo: local
      hooks:
      - id: ruff_check
        name: ruff_check
        entry: poetry run ruff check
        language: system
        pass_filenames: true
        types: [python]
      - id: ruff_format
        name: ruff_format
        entry: poetry run ruff format
        language: system
        pass_filenames: true
        types: [python]
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: system
        pass_filenames: false
        types: [python]
